import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "next.js-core-concepts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={roboto.className}
      >
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <footer className="bg-gray-500 py-6 text-white text-center text-xl">
          This it footer
        </footer>
      </body>
    </html>
  );
}
